apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  namespace: deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: ${REGION}-docker.pkg.dev/${PROJECT_ID}/${ARTIFACT_REPOSITORY}/api_service:${GITHUB_SHA}
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "1000m"
          volumeMounts:
            - name: gcp-sa-key
              mountPath: "/var/secrets"
          envFrom:
            - configMapRef:
                name: service-config-gke-deployment
      imagePullSecrets:
        - name: gcr-json-key-gke-deployment
      volumes:
        - name: gcp-sa-key
          secret:
            secretName: gcs-key-gke-deployment
---
apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: deployment
spec:
  type: ClusterIP
  selector:
    app: api
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
