name: Create GCP Service Account

on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/infra-sa-managed.yml'

jobs:
  create-sa:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Google Auth
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY_2 }}
  
      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
  

      - name: Create Service Account
        run: |
          SA_NAME="cloud-recommender-sa"
          PROJECT_ID="${{ secrets.GCP_PROJECT_ID }}"

          gcloud iam service-accounts create $SA_NAME \
            --display-name="Cloud Recommender Service Account"

      - name: Assign Roles to Service Account
        run: |
          SA_EMAIL="cloud-recommender-sa@${{ secrets.GCP_PROJECT_ID }}.iam.gserviceaccount.com"

          ROLES=(
            "roles/artifactregistry.admin"
            "roles/compute.networkAdmin"
            "roles/compute.securityAdmin"
            "roles/container.admin"
            "roles/iam.projectIamAdmin"
            "roles/iam.serviceAccountAdmin"
            "roles/iam.serviceAccountUser"
            "roles/servicemanagement.admin"
            "roles/serviceusage.serviceUsageAdmin"
            "roles/storage.admin"
          )

          for ROLE in "${ROLES[@]}"; do
            echo "Assigning $ROLE to $SA_EMAIL"
            gcloud projects add-iam-policy-binding "${{ secrets.GCP_PROJECT_ID }}" \
              --member="serviceAccount:$SA_EMAIL" \
              --role="$ROLE" \
              --quiet
          done
