name: Build and Deploy Recommender System

on:
  push:
    branches:
      - main  

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Docker image for UI service
        uses: docker/build-push-action@v5
        with:
          context: ./ui_service
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/ui:$(date-'%Y-%m-%d%H%M%S')

      - name: Build and push Docker image for API service
        uses: docker/build-push-action@v5
        with:
          context: ./api_service
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/api:$(date-'%Y-%m-%d%H%M%S')
      
      - name: Build and push Docker image for Recommender service
        uses: docker/build-push-action@v5
        with:
          context: ./recommender_service
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/model:$(date-'%Y-%m-%d%H%M%S')
      
      - name: Build and push Docker image for Preprocessing service
        uses: docker/build-push-action@v5
        with:
          context: ./preprocessing_service
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/preprocessing:$(date-'%Y-%m-%d%H%M%S')
